/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import chat.client.ChatClient;
import chat.server.ChatServer;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author human
 */
public class ChatFrame extends javax.swing.JFrame {

    private static final String SERVER_ADDRESS = "192.168.1.99";
    private static final int SERVER_PORT = 5781;
    private static final int CLIENT_SERVER_PORT = 5782;
    public String message;
    public String s;
    public String m;
    private ChatServer chatServer;
    public FileOutputStream fos;

    public ChatFrame() {
        initComponents();

        try {
            chatServer = new ChatServer(CLIENT_SERVER_PORT); // 5782
            new Thread(chatServer).start();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        // HACK
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaChatHistory = new javax.swing.JTextArea();
        jtfIPAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaChatMessage = new javax.swing.JTextArea();
        jbSendMessage = new javax.swing.JButton();
        jlStatusMessage = new javax.swing.JLabel();
        jbeChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtaChatHistory.setEditable(false);
        jtaChatHistory.setColumns(20);
        jtaChatHistory.setRows(14);
        jtaChatHistory.setFocusable(false);
        jScrollPane1.setViewportView(jtaChatHistory);

        jtfIPAddress.setText("192.168.1.");

        jLabel1.setText("IP Address:");

        jtaChatMessage.setColumns(20);
        jtaChatMessage.setRows(5);
        jtaChatMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaChatMessageKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtaChatMessage);

        jbSendMessage.setText("SEND");
        jbSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendMessageActionPerformed(evt);
            }
        });

        jbeChat.setText("END CHAT");
        jbeChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIPAddress))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbeChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSendMessage))
                    .addComponent(jlStatusMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSendMessage)
                    .addComponent(jbeChat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStatusMessage)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendMessageActionPerformed
        createFileHistory();
        String recipient = jtfIPAddress.getText();
        message = jtaChatMessage.getText();
        jtaChatHistory.setText("You:" + message);
        //writeMassegeClient();
        //writeMassageServer();
        if (message.isEmpty()) {
            jlStatusMessage.setText("Enter some message please before...");
            return;
        }

        ChatClient chatClient = new ChatClient(SERVER_ADDRESS, SERVER_PORT); // 5781
        try {
            chatClient.sendMessage(recipient, message);
        } catch (IOException ex) {
            Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtaChatMessage.setText(null);

    }//GEN-LAST:event_jbSendMessageActionPerformed

    private void jtaChatMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaChatMessageKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER && evt.isControlDown()) {
            evt.consume();

            jbSendMessageActionPerformed(null);
        }

    }//GEN-LAST:event_jtaChatMessageKeyPressed

    private void jbeChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeChatActionPerformed
        if (evt.getSource() == jbeChat) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbeChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbSendMessage;
    private javax.swing.JButton jbeChat;
    private javax.swing.JLabel jlStatusMessage;
    private javax.swing.JTextArea jtaChatHistory;
    private javax.swing.JTextArea jtaChatMessage;
    private javax.swing.JTextField jtfIPAddress;
    // End of variables declaration//GEN-END:variables
public void writeMassegeClient() {
        m = ChatClient.message;
        jtaChatHistory.setText("You:" + m);

        writeHistory();
    }

    public void writeMassageServer() {

        s = ChatServer.message;
        jtaChatHistory.setText("server" + s);

    }

    public void createFileHistory() {

        try {
            fos = new FileOutputStream("c:\\Users\\Глеб\\Documents\\NetBeansProjects\\Java-Chat-develop\\src\\chat\\History.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChatFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

   
    private void writeHistory() {
        while (true) {
            byte[] bytes = ChatClient.message.getBytes();
            byte[] bytes2 = m.getBytes();

            try {
                fos.write(bytes);
                fos.write('\n'); // write (int)
                fos.write(bytes2);
                fos.write('\n'); // write (int)
                fos.close();
                break;
            } catch (IOException ex) {
                jlStatusMessage.setText("cannot create file or write file");
            }
        }
    }
}
